package app

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"github.com/Ltre/MusicoletWeb/internal/db"
)

func (s *Service) recordChangeLocked(ctx context.Context,targetType,targetKey,operation string,before,after any,targets ...[2]string)error{b,_:=json.Marshal(before);a,_:=json.Marshal(after);_,_,vno,_:=s.Store.LatestVersion(ctx);var cid int64;if err:=s.Store.Tx(ctx,func(tx *sql.Tx)error{r,e:=tx.ExecContext(ctx,"INSERT INTO server_changes(base_version_id,target_type,target_key,operation,before_json,after_json,git_commit,active,created_at) SELECT id,?,?,?,?,?,NULL,1,? FROM musicolet_versions WHERE version_no=?",targetType,targetKey,operation,string(b),string(a),db.NowMS(),vno);if e!=nil{return e};cid,_=r.LastInsertId();if cid==0{return errors.New("server changes require an imported Musicolet base version")};all:=append([][2]string{{targetType,targetKey}},targets...);for _,t:=range all{_,_=tx.ExecContext(ctx,"INSERT OR IGNORE INTO change_targets(change_id,target_type,target_key) VALUES(?,?,?)",cid,t[0],t[1]);switch t[0]{case "song":_,_=tx.ExecContext(ctx,"UPDATE working_songs SET has_server_changes=1 WHERE path=?",t[1]);case "queue":_,_=tx.ExecContext(ctx,"UPDATE working_queues SET has_server_changes=1 WHERE name=?",t[1]);case "playlist":_,_=tx.ExecContext(ctx,"UPDATE working_playlists SET has_server_changes=1 WHERE name=?",t[1])}};return nil});err!=nil{return err};state,_:=s.loadWorking(ctx);sj,_:=json.Marshal(state);parent:=s.Git.Head("refs/heads/main");commit,e:=s.Git.CommitJSON("refs/heads/main",operation,sj,parent);if e!=nil{return e};_,e=s.Store.DB.ExecContext(ctx,"UPDATE server_changes SET git_commit=? WHERE id=?",commit,cid);return e}
func (s *Service) ReconcileGit(ctx context.Context)error{s.mutation.Lock();defer s.mutation.Unlock();rows,err:=s.Store.DB.QueryContext(ctx,"SELECT id,operation FROM server_changes WHERE git_commit IS NULL ORDER BY id");if err!=nil{return err};defer rows.Close();type pending struct{id int64;op string};var ps []pending;for rows.Next(){var p pending;if err=rows.Scan(&p.id,&p.op);err!=nil{return err};ps=append(ps,p)};for _,p:=range ps{state,e:=s.loadWorking(ctx);if e!=nil{return e};b,_:=json.Marshal(state);parent:=s.Git.Head("refs/heads/main");c,e:=s.Git.CommitJSON("refs/heads/main","reconcile: "+p.op,b,parent);if e!=nil{return e};if _,e=s.Store.DB.ExecContext(ctx,"UPDATE server_changes SET git_commit=? WHERE id=?",c,p.id);e!=nil{return e}};if _,_,vno,_:=s.Store.LatestVersion(ctx);vno>0{state,e:=s.loadWorking(ctx);if e!=nil{return e};current,_:=json.Marshal(state);gitState,e:=s.Git.ReadState("refs/heads/main");if e==nil&&!bytes.Equal(bytes.TrimSpace(gitState),bytes.TrimSpace(current)){parent:=s.Git.Head("refs/heads/main");c,e:=s.Git.CommitJSON("refs/heads/main","reconcile: unjournaled working-state drift",current,parent);if e!=nil{return e};_,_=s.Store.DB.ExecContext(ctx,"INSERT INTO server_changes(base_version_id,target_type,target_key,operation,before_json,after_json,git_commit,active,created_at) SELECT id,'system','working-state','RECOVER_WORKING_STATE',NULL,?,?,1,? FROM musicolet_versions WHERE version_no=?",string(current),c,db.NowMS(),vno)}};return nil}
