const TABS=[['queues','播放队列'],['now','正在播放'],['folders','文件夹'],['albums','专辑列表'],['artists','艺术家列表'],['genres','风格'],['playlists','歌曲清单'],['search','搜索'],['menu','☰']];let state={lib:null,play:null,tab:'queues',csrf:'',query:'',artistMode:'artist'};const $=s=>document.querySelector(s);function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function api(url,opt={}){opt.headers={...(opt.headers||{})};if(opt.body&&!(opt.body instanceof FormData)){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}if(['POST','PUT','DELETE','PATCH'].includes((opt.method||'GET').toUpperCase()))opt.headers['X-CSRF-Token']=state.csrf||cookie('mw_csrf');let r=await fetch(url,opt);let j=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw Error('auth')};if(!r.ok)throw Error(j.error||r.statusText);return j}function cookie(n){return document.cookie.split('; ').find(x=>x.startsWith(n+'='))?.split('=').slice(1).join('=')||''}
function showLogin(){ $('#login').classList.remove('hidden') }function hideLogin(){ $('#login').classList.add('hidden') }
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let x=await api('/api/auth/login',{method:'POST',body:{username:f.get('username'),password:f.get('password'),totp:f.get('totp')}});state.csrf=x.csrf;hideLogin();await reload()}catch(x){$('#loginErr').textContent=x.message}}
function tabs(){let el=$('#tabs');el.innerHTML=TABS.map(([k,n])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${n}</button>`).join('');el.onclick=e=>{let k=e.target.dataset.tab;if(k){state.tab=k;tabs();render()}}}
async function reload(){[state.lib,state.play]=await Promise.all([api('/api/library'),api('/api/playback')]);tabs();render()}
function songs(paths){return paths.map(p=>state.lib.songs[p]).filter(Boolean)}function songList(list,ctx={}){let q=state.query.toLowerCase();if(q)list=list.filter(s=>[s.title,s.artist,s.album,s.file_name,s.path].some(x=>(x||'').toLowerCase().includes(q)));return `<div>${list.map(s=>`<div class="song"><div data-play="${esc(s.path)}"><div class="song-title">${esc(s.title||s.file_name||s.path)}</div><div class="meta">${esc(s.artist)}${s.album?' · '+esc(s.album):''} · ${fmt(s.duration_ms)}</div></div><div class="song-actions"><button class="icon" data-fav="${esc(s.path)}">${state.lib.favorites[s.path]?'♥':'♡'}</button><button class="icon" data-more="${esc(s.path)}">⋮</button></div></div>`).join('')}</div><input class="search floating-search" id="viewSearch" value="${esc(state.query)}" placeholder="搜索当前视图歌曲...">`}
function bindSongs(ctx={}){$('#main').onclick=async e=>{let p=e.target.closest('[data-play]')?.dataset.play;if(p){await playFrom(ctx,p);return}let f=e.target.dataset.fav;if(f){let on=!state.lib.favorites[f];await api('/api/song/favorite',{method:'POST',body:{Path:f,On:on}});await reload();return}let m=e.target.dataset.more;if(m)showSongMenu(m,ctx)};let s=$('#viewSearch');if(s)s.oninput=e=>{state.query=e.target.value;render()}}
function showSongMenu(path,ctx){let s=state.lib.songs[path];let choice=prompt(`歌曲：${s.title}\n1 插队待播\n2 排到队尾\n3 此曲播完即停\n4 永久删除（仅服务器）\n输入编号：`);(async()=>{if(choice==='1'&&state.play.queue_id)await api('/api/queue/action',{method:'POST',body:{Action:'add',QueueID:state.play.queue_id,Path:path,Next:true}});if(choice==='2'&&state.play.queue_id)await api('/api/queue/action',{method:'POST',body:{Action:'add',QueueID:state.play.queue_id,Path:path}});if(choice==='3'&&state.play.queue_id)await api('/api/playback/stop-target',{method:'POST',body:{QueueID:state.play.queue_id,Path:path}});if(choice==='4'&&confirm('只会删除服务器曲库数据及其关联，不会修改手机文件。继续？'))await api('/api/song/delete',{method:'POST',body:{Path:path}});if(choice)await reload()})().catch(x=>toast(x.message))}
async function playFrom(ctx,path){if(ctx.sourceType){await api('/api/source/play',{method:'POST',body:{SourceType:ctx.sourceType,SourceKey:ctx.sourceKey,Name:ctx.name,Paths:ctx.paths,Path:path,Shuffle:false}})}else if(ctx.queueID){await api('/api/playback',{method:'POST',body:{queue_id:ctx.queueID,path,position_ms:0,playing:true}})}await reload();state.tab='now';tabs();render()}
