let shuffleBack=[],shuffleForward=[],shuffleQueueID=0,lastShuffleMode=false;
function render(){state.query='';let el=$('#main');if(!state.lib){el.textContent='加载中…';return}({queues:renderQueues,now:renderNow,folders:renderFolders,albums:renderAlbums,artists:renderArtists,genres:renderGenres,playlists:renderPlaylists,search:renderSearch,menu:renderMenu}[state.tab]||renderQueues)()}
function renderQueues(){
 let qs=state.lib.queues||[];if(!qs.length){$('#main').innerHTML='<p class="muted">暂无队列。导入 Musicolet Backup 后会显示。</p>';return}
 let q=qs.find(x=>x.id===state.viewQueueID)||qs.find(x=>x.id===state.play.queue_id)||qs[0];state.viewQueueID=q.id;let qi=qs.findIndex(x=>x.id===q.id);
 $('#main').innerHTML=`<div class="queue-head"><button class="primary" id="continueQ">▶</button><select id="queueSel">${qs.map(x=>`<option value="${x.id}" ${x.id===q.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><span>${q.current_index+1}/${q.paths.length}</span><button id="renameQ">改名</button><button id="upQ" ${qi<=0?'disabled':''}>↑</button><button id="downQ" ${qi>=qs.length-1?'disabled':''}>↓</button><button id="delQ">删除</button></div><div class="toolbar"><button id="reverseQ">反向</button><button id="shuffleQ">随机化</button>${q.stop_path?`<span class="muted">将在 ${esc(state.lib.songs[q.stop_path]?.title||q.stop_path)} 播完后停止</span>`:''}</div>${songList(songs(q.paths),{queueID:q.id,paths:q.paths})}`;
 $('#queueSel').onchange=e=>{state.viewQueueID=+e.target.value;renderQueues()};
 $('#continueQ').onclick=()=>{let p=q.paths[q.current_index]||q.paths[0]||'';api('/api/playback',{method:'POST',body:{queue_id:q.id,path:p,position_ms:q.position_ms||0,playing:true}}).then(reload)};
 $('#renameQ').onclick=async()=>{let n=prompt('队列名称',q.name);if(n&&n!==q.name){await api('/api/queue/action',{method:'POST',body:{Action:'rename',QueueID:q.id,Name:n}});await reload()}};
 $('#upQ').onclick=()=>api('/api/queue/action',{method:'POST',body:{Action:'move_queue',QueueID:q.id,Position:qi-1}}).then(reload);
 $('#downQ').onclick=()=>api('/api/queue/action',{method:'POST',body:{Action:'move_queue',QueueID:q.id,Position:qi+1}}).then(reload);
 $('#delQ').onclick=()=>confirm('删除这个队列？')&&api('/api/queue/action',{method:'POST',body:{Action:'delete',QueueID:q.id}}).then(()=>{state.viewQueueID=0;return reload()});
 $('#reverseQ').onclick=()=>api('/api/queue/action',{method:'POST',body:{Action:'reverse',QueueID:q.id,Order:q.paths}}).then(reload);
 $('#shuffleQ').onclick=()=>{let a=[...q.paths];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return api('/api/queue/action',{method:'POST',body:{Action:'randomize',QueueID:q.id,Order:a}}).then(reload)};
 bindSongs({queueID:q.id,paths:q.paths})
}
function mediaUnavailable(){toast('无法播放：手机 Agent 已离线或当前歌曲不可读取')}
function resetShuffleHistory(queueID,mode){shuffleBack=[];shuffleForward=[];shuffleQueueID=queueID||0;lastShuffleMode=!!mode}
function syncShuffleHistory(p){if(shuffleQueueID!==p.queue_id||lastShuffleMode!==!!p.shuffle)resetShuffleHistory(p.queue_id,p.shuffle)}
function randomOther(paths,current){let candidates=paths.filter(x=>x!==current);if(!candidates.length)return current||paths[0]||'';return candidates[Math.floor(Math.random()*candidates.length)]}
function renderNow(){let p=state.play,s=p.song,agentOnline=!!state.health?.agent_online;syncShuffleHistory(p);$('#main').innerHTML=`<div class="now"><div class="cover">♪</div><h2>${esc(s?.title||'暂无播放')}</h2><div class="muted">${esc(s?.artist||'')}${s?.album?' · '+esc(s.album):''}</div>${s&&!agentOnline?'<div class="error">手机 Agent 当前离线；如果浏览器没有已缓存媒体，当前歌曲无法播放。</div>':''}<div class="now-controls"><button id="prev">⏮</button><button id="rewind">↶ 10s</button><button id="toggle">${p.playing?'⏸':'▶'}</button><button id="forward">10s ↷</button><button id="next">⏭</button></div>${s?`<audio id="audio" controls preload="metadata" src="/api/media?path=${encodeURIComponent(p.path)}"></audio>`:''}<div class="toolbar"><button id="favNow">${state.lib.favorites[p.path]?'♥':'♡'}</button><select id="speed">${[.25,.5,.75,1,1.25,1.5,1.75,2].map(x=>`<option ${p.speed===x?'selected':''}>${x}</option>`).join('')}</select><button id="shuffle">${p.shuffle?'随机':'顺序'}</button><select id="loop"><option value="list">列表循环</option><option value="single">单曲循环</option><option value="stop">此曲播完即停</option></select></div></div>`;let a=$('#audio');if(a){a.currentTime=(p.position_ms||0)/1000;a.playbackRate=p.speed||1;a.onplay=()=>setPlay(true);a.onpause=()=>setPlay(false);a.onerror=mediaUnavailable;a.ontimeupdate=()=>{if(Math.floor(a.currentTime)%5===0)savePos(a.currentTime)};a.onended=()=>ended()};$('#toggle').onclick=()=>{if(!a){mediaUnavailable();return}if(a.paused)a.play().catch(mediaUnavailable);else a.pause()};$('#rewind').onclick=()=>seekBy(-10);$('#forward').onclick=()=>seekBy(10);$('#speed').onchange=e=>api('/api/playback/mode',{method:'POST',body:{shuffle:p.shuffle,loop:p.loop_mode,speed:+e.target.value}}).then(reload);$('#shuffle').onclick=()=>api('/api/playback/mode',{method:'POST',body:{shuffle:!p.shuffle,loop:p.loop_mode,speed:p.speed}}).then(reload);$('#loop').value=p.loop_mode;$('#loop').onchange=e=>api('/api/playback/mode',{method:'POST',body:{shuffle:p.shuffle,loop:e.target.value,speed:p.speed}}).then(reload);$('#favNow').onclick=()=>api('/api/song/favorite',{method:'POST',body:{Path:p.path,On:!state.lib.favorites[p.path]}}).then(reload);$('#next').onclick=()=>step(1);$('#prev').onclick=()=>step(-1)}
async function seekBy(seconds){let a=$('#audio');if(!a){mediaUnavailable();return}let max=Number.isFinite(a.duration)&&a.duration>0?a.duration:(state.play.song?.duration_ms||0)/1000;if(!max||max<0)max=Number.POSITIVE_INFINITY;let target=Math.max(0,Math.min(max,a.currentTime+seconds));a.currentTime=target;await savePos(target)}
async function savePos(t){if(!state.play.queue_id)return;await api('/api/playback',{method:'POST',body:{queue_id:state.play.queue_id,path:state.play.path,position_ms:Math.round(t*1000),playing:!$('#audio')?.paused}}).catch(()=>{})}async function setPlay(v){if(state.play.queue_id)await api('/api/playback',{method:'POST',body:{queue_id:state.play.queue_id,path:state.play.path,position_ms:Math.round(($('#audio')?.currentTime||0)*1000),playing:v}})}
async function step(d){let q=state.lib.queues.find(x=>x.id===state.play.queue_id);if(!q||!q.paths.length)return;let current=state.play.path,next='';if(state.play.shuffle&&q.paths.length>1){syncShuffleHistory(state.play);if(d<0&&shuffleBack.length){next=shuffleBack.pop();shuffleForward.push(current)}else if(d>0&&shuffleForward.length){next=shuffleForward.pop();shuffleBack.push(current)}else{next=randomOther(q.paths,current);if(d<0)shuffleForward.push(current);else shuffleBack.push(current)}}else{let i=q.paths.indexOf(current);if(i<0)i=0;let n=(i+d+q.paths.length)%q.paths.length;next=q.paths[n]}if(!next)return;await api('/api/playback',{method:'POST',body:{queue_id:q.id,path:next,position_ms:0,playing:true}});await reload();renderNow()}
async function ended(){if(state.play.path)await api('/api/song/played',{method:'POST',body:{Path:state.play.path}});if(state.play.stop_path===state.play.path||state.play.loop_mode==='stop'){await setPlay(false);return}if(state.play.loop_mode==='single'){let a=$('#audio');a.currentTime=0;a.play().catch(mediaUnavailable);return}step(1)}
