const TABS=[['queues','播放队列'],['now','正在播放'],['folders','文件夹'],['albums','专辑列表'],['artists','艺术家列表'],['genres','风格'],['playlists','歌曲清单'],['search','搜索'],['menu','☰']];let state={lib:null,play:null,health:{agent_online:false},tab:'queues',csrf:'',query:'',artistMode:'artist',viewQueueID:0};const SONG_BATCH=250;let activeSongView=null;const $=s=>document.querySelector(s);function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function api(url,opt={}){opt.headers={...(opt.headers||{})};if(opt.body&&!(opt.body instanceof FormData)){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}if(['POST','PUT','DELETE','PATCH'].includes((opt.method||'GET').toUpperCase()))opt.headers['X-CSRF-Token']=state.csrf||cookie('mw_csrf');let r=await fetch(url,opt);let j=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw Error('auth')};if(!r.ok)throw Error(j.error||r.statusText);return j}function cookie(n){return document.cookie.split('; ').find(x=>x.startsWith(n+'='))?.split('=').slice(1).join('=')||''}
function showLogin(){ $('#login').classList.remove('hidden') }function hideLogin(){ $('#login').classList.add('hidden') }
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let x=await api('/api/auth/login',{method:'POST',body:{username:f.get('username'),password:f.get('password'),totp:f.get('totp')}});state.csrf=x.csrf;hideLogin();await reload()}catch(x){$('#loginErr').textContent=x.message}}
function tabs(){let el=$('#tabs');el.innerHTML=TABS.map(([k,n])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${n}</button>`).join('');el.onclick=e=>{let k=e.target.dataset.tab;if(k){state.tab=k;state.query='';activeSongView=null;tabs();render()}}}
async function reload(){[state.lib,state.play,state.health]=await Promise.all([api('/api/library'),api('/api/playback'),api('/api/health')]);tabs();render()}
function songForPath(path){let s=state.lib.songs[path];if(s)return s;let file=path;try{file=decodeURIComponent(path).split('/').pop()||path}catch{}return {path,title:'[源曲库已不存在]',file_name:file,artist:'',album:'',duration_ms:0,missing:true}}function songs(paths){return paths.map(songForPath)}
function filterSongView(list){let q=state.query.trim().toLowerCase();if(!q)return list;return list.filter(s=>[s.title,s.artist,s.album,s.file_name,s.path].some(x=>(x||'').toLowerCase().includes(q)))}
function songRow(s){let current=state.play?.path===s.path?' current-song':'';return `<div class="song${s.missing?' missing-song':''}${current}"><div ${s.missing?'':`data-play="${esc(s.path)}"`}><div class="song-title">${esc(s.title||s.file_name||s.path)}</div><div class="meta">${s.missing?`源备份仍保留此路径 · ${esc(s.path)}`:`${esc(s.artist)}${s.album?' · '+esc(s.album):''} · ${fmt(s.duration_ms)}`}</div></div><div class="song-actions"><button class="icon" data-fav="${esc(s.path)}">${state.lib.favorites[s.path]?'♥':'♡'}</button><button class="icon" data-more="${esc(s.path)}">⋮</button></div></div>`}
function songList(list,ctx={}){activeSongView={source:list,filtered:filterSongView(list),rendered:0,ctx};let first=activeSongView.filtered.slice(0,SONG_BATCH);activeSongView.rendered=first.length;let more=activeSongView.rendered<activeSongView.filtered.length?`<button id="songMore" class="load-more">继续显示（${activeSongView.rendered}/${activeSongView.filtered.length}）</button>`:'';return `<div id="songRows">${first.map(songRow).join('')}</div>${more}<input class="search floating-search" id="viewSearch" value="${esc(state.query)}" placeholder="搜索当前视图歌曲...">`}
function loadMoreSongs(){let v=activeSongView,box=$('#songRows'),more=$('#songMore');if(!v||!box||!more)return;let next=v.filtered.slice(v.rendered,v.rendered+SONG_BATCH);box.insertAdjacentHTML('beforeend',next.map(songRow).join(''));v.rendered+=next.length;if(v.rendered>=v.filtered.length){more.remove();return}more.textContent=`继续显示（${v.rendered}/${v.filtered.length}）`}
function resetSongRows(){let v=activeSongView,box=$('#songRows');if(!v||!box)return;v.filtered=filterSongView(v.source);v.rendered=Math.min(SONG_BATCH,v.filtered.length);box.innerHTML=v.filtered.slice(0,v.rendered).map(songRow).join('');let more=$('#songMore');if(v.rendered<v.filtered.length){if(!more){more=document.createElement('button');more.id='songMore';more.className='load-more';box.insertAdjacentElement('afterend',more)}more.textContent=`继续显示（${v.rendered}/${v.filtered.length}）`}else if(more)more.remove();bindSongMoreObserver()}
function bindSongMoreObserver(){let more=$('#songMore');if(!more)return;more.onclick=loadMoreSongs;if(!('IntersectionObserver'in window))return;let io=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting)){loadMoreSongs();let current=$('#songMore');if(!current)io.disconnect();else{io.disconnect();bindSongMoreObserver()}}},{rootMargin:'600px'});io.observe(more)}
function bindSongs(ctx={}){$('#main').onclick=async e=>{if(e.target.id==='songMore'){loadMoreSongs();return}let p=e.target.closest('[data-play]')?.dataset.play;if(p){await playFrom(ctx,p);return}let f=e.target.dataset.fav;if(f){let on=!state.lib.favorites[f];await api('/api/song/favorite',{method:'POST',body:{Path:f,On:on}});await reload();return}let m=e.target.dataset.more;if(m)showSongMenu(m,ctx)};let s=$('#viewSearch');if(s)s.oninput=e=>{state.query=e.target.value;resetSongRows()};bindSongMoreObserver()}
function showSongMenu(path,ctx={}){let s=songForPath(path);let personal=ctx.playlistName&&!ctx.system;if(s.missing){if(!personal){toast('该路径仍存在于源关系中，但已不在当前 All songs；可用心形按钮移出喜爱');return}let choice=prompt(`该歌曲路径已不在当前 All songs，但源歌单关系仍保留：\n${path}\n\n1 移出当前歌单\n2 调整当前歌单位置\n输入编号：`);(async()=>{if(choice==='1')await api('/api/playlist/action',{method:'POST',body:{Name:ctx.playlistName,Action:'remove',Path:path}});else if(choice==='2'){let pos=prompt(`移动到第几首（1-${ctx.paths.length}）`,String(Math.max(1,ctx.paths.indexOf(path)+1)));if(pos!==null){let n=Number(pos);if(!Number.isInteger(n)||n<1||n>ctx.paths.length)throw Error('位置无效');await api('/api/playlist/action',{method:'POST',body:{Name:ctx.playlistName,Action:'move',Path:path,Position:n-1}})}}if(choice)await reload()})().catch(x=>toast(x.message));return}let lines=['1 插队待播','2 排到队尾','3 此曲播完即停','4 编辑元数据（仅服务器）','5 加入个人歌单'];if(personal)lines.push('6 移出当前歌单','7 调整当前歌单位置');lines.push('9 永久删除（仅服务器）');let choice=prompt(`歌曲：${s.title||s.file_name||path}\n${lines.join('\n')}\n输入编号：`);(async()=>{if(choice==='1'&&state.play.queue_id)await api('/api/queue/action',{method:'POST',body:{Action:'add',QueueID:state.play.queue_id,Path:path,Next:true}});else if(choice==='2'&&state.play.queue_id)await api('/api/queue/action',{method:'POST',body:{Action:'add',QueueID:state.play.queue_id,Path:path}});else if(choice==='3'&&state.play.queue_id)await api('/api/playback/stop-target',{method:'POST',body:{QueueID:state.play.queue_id,Path:path}});else if(choice==='4')await editMetadata(path);else if(choice==='5')await addSongToPlaylist(path);else if(choice==='6'&&personal)await api('/api/playlist/action',{method:'POST',body:{Name:ctx.playlistName,Action:'remove',Path:path}});else if(choice==='7'&&personal){let pos=prompt(`移动到第几首（1-${ctx.paths.length}）`,String(Math.max(1,ctx.paths.indexOf(path)+1)));if(pos!==null){let n=Number(pos);if(!Number.isInteger(n)||n<1||n>ctx.paths.length)throw Error('位置无效');await api('/api/playlist/action',{method:'POST',body:{Name:ctx.playlistName,Action:'move',Path:path,Position:n-1}})}}else if(choice==='9'&&confirm('只会删除服务器曲库数据及其关联，不会修改手机文件。继续？'))await api('/api/song/delete',{method:'POST',body:{Path:path}});if(choice)await reload()})().catch(x=>toast(x.message))}
async function editMetadata(path){let s=state.lib.songs[path];if(!s)throw Error('该源路径已不在当前 All songs，不能编辑 Metadata');let editable={title:s.title||'',artist:s.artist||'',album:s.album||'',album_artist:s.album_artist||'',composer:s.composer||'',genre:s.genre||'',lyrics:s.lyrics||'',track_no:s.track_no||'',disc_no:s.disc_no||'',year:s.year||'',comment:s.comment||'',duration_ms:s.duration_ms||0};let txt=prompt('编辑服务器中的歌曲元数据（JSON）。不会修改手机文件原 Metadata。',JSON.stringify(editable,null,2));if(txt===null)return;let song;try{song=JSON.parse(txt)}catch{throw Error('元数据 JSON 格式错误')}await api('/api/song/metadata',{method:'POST',body:{path,song}})}
async function addSongToPlaylist(path){let pls=(state.lib.playlists||[]).map(x=>x.name);if(!pls.length)throw Error('暂无个人歌单，请先在“歌曲清单”中新建');let name=prompt(`加入个人歌单：\n${pls.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n输入歌单名称：`,pls[0]);if(!name)return;if(!pls.includes(name))throw Error('个人歌单不存在');await api('/api/playlist/action',{method:'POST',body:{Name:name,Action:'add',Path:path}})}
async function playFrom(ctx,path){if(!state.lib.songs[path])throw Error('该源路径已不在当前 All songs，不能播放');if(ctx.sourceType){await api('/api/source/play',{method:'POST',body:{SourceType:ctx.sourceType,SourceKey:ctx.sourceKey,Name:ctx.name,Paths:ctx.paths,Path:path,Shuffle:false}})}else if(ctx.queueID){await api('/api/playback',{method:'POST',body:{queue_id:ctx.queueID,path,position_ms:0,playing:true}})}await reload();state.tab='now';tabs();render()}
